# Generated by Django 3.1.7 on 2022-04-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='phoneNumber',
            field=models.CharField(default='', max_length=15),
        ),
    ]
