# Generated by Django 3.1.7 on 2022-04-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20220412_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
