# Generated by Django 3.1.7 on 2022-05-07 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_mensagens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='startDate',
        ),
        migrations.CreateModel(
            name='calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.reservation')),
            ],
        ),
    ]
