# Generated by Django 3.1.7 on 2022-05-07 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0005_auto_20220507_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservationName',
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
