# Generated by Django 3.1.7 on 2022-05-07 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20220507_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='luagr',
            new_name='lugar',
        ),
    ]
