# Generated by Django 3.1.7 on 2022-05-07 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20220507_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='lugar',
        ),
        migrations.DeleteModel(
            name='chair',
        ),
    ]
