# Generated by Django 3.1.7 on 2022-05-12 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0010_auto_20220507_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='meetingRooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='meetingRoomCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('sala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.meetingrooms')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
