# Generated by Django 3.1.7 on 2022-05-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_meetingroomcalendar_meetingrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroomcalendar',
            name='endTime',
            field=models.TimeField(),
        ),
    ]
