# Generated by Django 3.1.7 on 2022-05-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20220512_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingrooms',
            name='ids',
            field=models.CharField(blank=True, choices=[('', ''), ('1', '1'), ('2', '2')], max_length=10),
        ),
    ]
