# Generated by Django 3.1.7 on 2022-05-12 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20220512_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroomcalendar',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.chair'),
        ),
        migrations.AlterField(
            model_name='meetingroomcalendar',
            name='startTime',
            field=models.TimeField(),
        ),
    ]
