# Generated by Django 3.1.7 on 2022-05-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_mensagens_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagens',
            name='Pendente',
            field=models.BooleanField(default=True),
        ),
    ]
