# Generated by Django 3.1.7 on 2022-05-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_mensagens_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagens',
            name='Reason',
            field=models.CharField(default='contacto', max_length=50),
        ),
    ]
