# Generated by Django 3.1.7 on 2022-05-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_mensagens_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='nrDias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calendar',
            name='nrLugares',
            field=models.IntegerField(default=0),
        ),
    ]
