# Generated by Django 3.1.7 on 2022-05-16 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0019_auto_20220516_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='nrLugares',
        ),
        migrations.CreateModel(
            name='reservas_Coworking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrLugares', models.IntegerField(default=0)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('valor', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
