# Generated by Django 3.1.7 on 2022-05-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20220516_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas_coworking',
            name='nrDias',
            field=models.IntegerField(default=0),
        ),
    ]
