# Generated by Django 3.1.7 on 2022-05-30 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_reservas_coworking_provisoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas_coworking',
            name='nrLugares',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.calendar'),
        ),
    ]
