# Generated by Django 3.1.7 on 2022-05-31 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_auto_20220530_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas_coworking',
            name='nrLugares',
            field=models.IntegerField(default=0),
        ),
    ]
