# Generated by Django 3.1.7 on 2022-06-07 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_auto_20220531_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservas_coworking',
            name='nrLugares',
        ),
    ]
