# Generated by Django 3.1.7 on 2022-06-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_remove_reservas_coworking_nrlugares'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas_coworking',
            name='nrLugares',
            field=models.IntegerField(default=0),
        ),
    ]
