# Generated by Django 4.0.5 on 2022-06-15 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_alter_reservas_coworking_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservas_coworking',
            old_name='price',
            new_name='cost_price',
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_price_id', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.reservas_coworking')),
            ],
        ),
    ]
