# Generated by Django 4.0.5 on 2022-06-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_rename_price_reservas_coworking_cost_price_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas_coworking_provisoria',
            name='chair1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservas_coworking_provisoria',
            name='chair10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservas_coworking_provisoria',
            name='chair11',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservas_coworking_provisoria',
            name='chair12z',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservas_coworking_provisoria',
            name='chair2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservas_coworking_provisoria',
            name='chair3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservas_coworking_provisoria',
            name='chair4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservas_coworking_provisoria',
            name='chair5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservas_coworking_provisoria',
            name='chair6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservas_coworking_provisoria',
            name='chair7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservas_coworking_provisoria',
            name='chair8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservas_coworking_provisoria',
            name='chair9',
            field=models.BooleanField(default=False),
        ),
    ]
