# Generated by Django 3.1.7 on 2022-06-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0030_rename_price_reservas_coworking_cost_price_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas_coworking_provisoria',
            name='chair1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservas_coworking_provisoria',
            name='chair10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservas_coworking_provisoria',
            name='chair11',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservas_coworking_provisoria',
            name='chair12',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservas_coworking_provisoria',
            name='chair2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservas_coworking_provisoria',
            name='chair3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservas_coworking_provisoria',
            name='chair4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservas_coworking_provisoria',
            name='chair5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservas_coworking_provisoria',
            name='chair6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservas_coworking_provisoria',
            name='chair7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservas_coworking_provisoria',
            name='chair8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservas_coworking_provisoria',
            name='chair9',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservas_coworking_provisoria',
            name='nrLugares',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chair',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='meetingroomcalendar',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='meetingrooms',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mensagens',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='price',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reservas_coworking',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reservas_coworking_provisoria',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
