# Generated by Django 4.0.5 on 2022-06-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0031_reservas_coworking_provisoria_chair1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservas_coworking_provisoria',
            old_name='chair12z',
            new_name='chair12',
        ),
        migrations.AddField(
            model_name='reservas_coworking_provisoria',
            name='nrLugares',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
