# Generated by Django 4.0.5 on 2022-06-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0032_rename_chair12z_reservas_coworking_provisoria_chair12_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservas_coworking',
            name='endDate',
        ),
        migrations.AddField(
            model_name='reservas_coworking',
            name='pacote',
            field=models.CharField(blank=True, choices=[('', ''), ('Semanal', 'Semanal'), ('Mensal', 'Mensal'), ('Trimestral', 'Trimestral')], max_length=15),
        ),
    ]
