# Generated by Django 4.0.5 on 2022-06-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0034_remove_reservas_coworking_provisoria_enddate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservas_coworking_provisoria',
            name='chair1',
        ),
        migrations.RemoveField(
            model_name='reservas_coworking_provisoria',
            name='chair10',
        ),
        migrations.RemoveField(
            model_name='reservas_coworking_provisoria',
            name='chair11',
        ),
        migrations.RemoveField(
            model_name='reservas_coworking_provisoria',
            name='chair12',
        ),
        migrations.RemoveField(
            model_name='reservas_coworking_provisoria',
            name='chair2',
        ),
        migrations.RemoveField(
            model_name='reservas_coworking_provisoria',
            name='chair3',
        ),
        migrations.RemoveField(
            model_name='reservas_coworking_provisoria',
            name='chair4',
        ),
        migrations.RemoveField(
            model_name='reservas_coworking_provisoria',
            name='chair5',
        ),
        migrations.RemoveField(
            model_name='reservas_coworking_provisoria',
            name='chair6',
        ),
        migrations.RemoveField(
            model_name='reservas_coworking_provisoria',
            name='chair7',
        ),
        migrations.RemoveField(
            model_name='reservas_coworking_provisoria',
            name='chair8',
        ),
        migrations.RemoveField(
            model_name='reservas_coworking_provisoria',
            name='chair9',
        ),
        migrations.AddField(
            model_name='reservas_coworking_provisoria',
            name='endDate',
            field=models.DateField(null=True),
        ),
    ]
