# Generated by Django 4.0.5 on 2022-06-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0035_remove_reservas_coworking_provisoria_chair1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas_coworking_provisoria',
            name='lugares',
            field=models.CharField(blank=True, choices=[('', ''), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=15),
        ),
    ]
