# Generated by Django 4.0.5 on 2022-06-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0036_reservas_coworking_provisoria_lugares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas_coworking_provisoria',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
