# Generated by Django 4.0.5 on 2022-06-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0038_remove_reservas_coworking_provisoria_lugares_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas_coworking',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
