# Generated by Django 3.1.7 on 2022-06-20 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0039_reservas_coworking_enddate'),
        ('polls', '0031_auto_20220615_1612'),
    ]

    operations = [
    ]
