# Generated by Django 3.1.7 on 2022-06-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0040_merge_20220620_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas_coworking_provisoria',
            name='nrLugares',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='calendar',
        ),
        migrations.DeleteModel(
            name='chair',
        ),
    ]
