# Generated by Django 3.2 on 2022-06-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0042_auto_20220621_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas_coworking_provisoria',
            name='qty',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
