# Generated by Django 3.2 on 2022-06-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0044_auto_20220621_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas_coworking_provisoria',
            name='nrPacotes',
            field=models.IntegerField(default=0),
        ),
    ]
