# Generated by Django 3.2 on 2022-06-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0045_alter_reservas_coworking_provisoria_nrpacotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas_coworking_provisoria',
            name='nrPacotes',
            field=models.IntegerField(default=1),
        ),
    ]
