# Generated by Django 3.2 on 2022-06-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0046_alter_reservas_coworking_provisoria_nrpacotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas_coworking_provisoria',
            name='second_step',
            field=models.BooleanField(default=False),
        ),
    ]
