# Generated by Django 3.1.7 on 2022-07-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0049_auto_20220706_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas_coworking_provisoria',
            name='checkout_step',
            field=models.BooleanField(default=False),
        ),
    ]
