# Generated by Django 3.1.7 on 2022-07-07 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0050_reservas_coworking_provisoria_checkout_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservas_coworking_provisoria',
            name='checkout_step',
        ),
        migrations.CreateModel(
            name='reservas_Coworking_Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(blank=True, null=True)),
                ('pacote', models.CharField(blank=True, choices=[('', ''), ('Semanal', 'Semanal'), ('Mensal', 'Mensal'), ('Trimestral', 'Trimestral')], max_length=15)),
                ('nrPacotes', models.PositiveIntegerField(default=1)),
                ('chair1', models.BooleanField(default=False)),
                ('chair2', models.BooleanField(default=False)),
                ('chair3', models.BooleanField(default=False)),
                ('chair4', models.BooleanField(default=False)),
                ('chair5', models.BooleanField(default=False)),
                ('chair6', models.BooleanField(default=False)),
                ('chair7', models.BooleanField(default=False)),
                ('chair8', models.BooleanField(default=False)),
                ('chair9', models.BooleanField(default=False)),
                ('chair10', models.BooleanField(default=False)),
                ('chair11', models.BooleanField(default=False)),
                ('chair12', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
