# Generated by Django 3.1.7 on 2022-07-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0051_auto_20220707_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas_coworking_process',
            name='cost_price',
            field=models.IntegerField(default=0),
        ),
    ]
