# Generated by Django 3.1.7 on 2022-07-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0052_reservas_coworking_process_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas_coworking',
            name='nrPacotes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
