# Generated by Django 3.1.7 on 2022-07-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0054_reservas_coworking_provisoria_cost_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservas_coworking',
            name='name',
        ),
    ]
