# Generated by Django 3.1.7 on 2022-07-08 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0055_remove_reservas_coworking_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reservas_Coworking_Process',
        ),
    ]
