# Generated by Django 3.1.7 on 2022-07-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0056_delete_reservas_coworking_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pacote', models.CharField(blank=True, choices=[('', ''), ('Semanal', 'Semanal'), ('Mensal', 'Mensal'), ('Trimestral', 'Trimestral')], max_length=15)),
                ('cost_price', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
