# Generated by Django 3.1.7 on 2022-07-08 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0057_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='Product',
        ),
    ]
