# Generated by Django 3.1.7 on 2022-07-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0058_auto_20220708_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pacote',
        ),
        migrations.RemoveField(
            model_name='reservas_coworking',
            name='nrPacotes',
        ),
        migrations.AddField(
            model_name='product',
            name='nrPacotes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
