# Generated by Django 3.1.7 on 2022-07-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0059_auto_20220708_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='nrPacotes',
        ),
        migrations.AddField(
            model_name='product',
            name='chair1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='chair10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='chair11',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='chair12',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='chair2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='chair3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='chair4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='chair5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='chair6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='chair7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='chair8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='chair9',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='nrDias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='nrLugares',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='pacote',
            field=models.CharField(blank=True, choices=[('', ''), ('Semanal', 'Semanal'), ('Mensal', 'Mensal'), ('Trimestral', 'Trimestral')], max_length=15),
        ),
        migrations.AddField(
            model_name='product',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
