# Generated by Django 3.1.7 on 2022-07-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0065_auto_20220708_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas_coworking',
            name='nrPacotes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
