# Generated by Django 3.1.7 on 2022-07-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0068_auto_20220725_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservas_coworking',
            name='nrPacotes',
        ),
        migrations.RemoveField(
            model_name='reservas_coworking',
            name='pacote',
        ),
        migrations.RemoveField(
            model_name='reservas_coworking_provisoria',
            name='nrPacotes',
        ),
        migrations.RemoveField(
            model_name='reservas_coworking_provisoria',
            name='pacote',
        ),
        migrations.AddField(
            model_name='reservas_coworking_provisoria',
            name='nrDias',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
