# Generated by Django 3.1.7 on 2022-07-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0069_auto_20220728_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pacote',
        ),
        migrations.AlterField(
            model_name='reservas_coworking_provisoria',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
