# Generated by Django 3.1.7 on 2022-07-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0071_remove_reservas_coworking_provisoria_enddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservas_coworking',
            name='endDate',
        ),
        migrations.AddField(
            model_name='reservas_coworking_provisoria',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
