# Generated by Django 3.1.7 on 2022-07-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0072_auto_20220729_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas_coworking',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservas_coworking',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
