# Generated by Django 4.0.6 on 2022-08-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='mettingRoomHours',
            field=models.DateTimeField(null=True),
        ),
    ]
