# Generated by Django 4.0.6 on 2022-08-23 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservas', '0004_alter_wallet_mettingroomhours'),
    ]

    operations = [
        migrations.CreateModel(
            name='meetingRoomProvisoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('sala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.meetingrooms')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
