# Generated by Django 4.0.6 on 2022-08-29 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_alter_wallet_mettingroomhours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='mettingRoomHours',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
