# Generated by Django 4.0.6 on 2022-08-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_alter_wallet_mettingroomhours'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='mettingRoomMinutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='mettingRoomHours',
            field=models.IntegerField(default=0),
        ),
    ]
