# Generated by Django 3.2 on 2022-09-02 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_wallet_mettingroomminutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='mettingRoomHours',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='mettingRoomMinutes',
        ),
    ]
