# Generated by Django 3.2 on 2022-09-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_auto_20220902_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='mettingRoomHours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='mettingRoomMinutes',
            field=models.IntegerField(default=0),
        ),
    ]
