# Generated by Django 4.1.1 on 2022-09-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0010_auto_20220902_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcmeWebhookMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='reservas_coworking_provisoria',
            name='transactionId',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
