# Generated by Django 4.1.1 on 2022-09-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0011_acmewebhookmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas_coworking_provisoria',
            name='transactionId',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
