# Generated by Django 4.1.1 on 2022-09-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0012_alter_reservas_coworking_provisoria_transactionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas_coworking',
            name='cost_price',
            field=models.FloatField(default=0.0),
        ),
    ]
