# Generated by Django 4.1.1 on 2022-09-08 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservas', '0014_meetingroomcalendar_cost_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bundleProvisorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_5', models.BooleanField(default=False)),
                ('bundle_10', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
