# Generated by Django 4.1.1 on 2022-09-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0016_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('', ''), ('pending', 'pending'), ('success', 'success'), ('declined', 'declined')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('', ''), ('mb_way', 'mb_way'), ('multibanco', 'multibanco'), ('cartão', 'cartão')], max_length=50, null=True),
        ),
    ]
