# Generated by Django 4.1.1 on 2022-09-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0017_alter_transaction_status_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transactionId',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='mettingRoomDays',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('', ''), ('Pending', 'Pending'), ('Success', 'Success'), ('Declined', 'Declined')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('', ''), ('MBWAY', 'MBWAY'), ('REFERENCE', 'REFERENCE'), ('CARD', 'CARD')], max_length=50, null=True),
        ),
    ]
