# Generated by Django 4.1.1 on 2022-09-09 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0018_transaction_transactionid_wallet_mettingroomdays_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='mettingRoomDays',
        ),
    ]
