# Generated by Django 4.1.1 on 2022-09-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0019_remove_wallet_mettingroomdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroomprovisoria',
            name='endAm_Pm',
            field=models.CharField(choices=[('', ''), ('AM', 'AM'), ('PM', 'PM')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='meetingroomprovisoria',
            name='endHour',
            field=models.CharField(choices=[('', ''), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '11'), ('12', '12')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='meetingroomprovisoria',
            name='endMinute',
            field=models.CharField(choices=[('', ''), ('0', '0'), ('30', '30')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='meetingroomprovisoria',
            name='startAm_PM',
            field=models.CharField(choices=[('', ''), ('AM', 'AM'), ('PM', 'PM')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='meetingroomprovisoria',
            name='startHour',
            field=models.CharField(choices=[('', ''), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '11'), ('12', '12')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='meetingroomprovisoria',
            name='startMinute',
            field=models.CharField(choices=[('', ''), ('0', '0'), ('30', '30')], max_length=50, null=True),
        ),
    ]
