# Generated by Django 4.1.1 on 2022-09-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0020_meetingroomprovisoria_endam_pm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroomprovisoria',
            name='endMinute',
            field=models.CharField(choices=[('', ''), ('00', '00'), ('30', '30')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='meetingroomprovisoria',
            name='startMinute',
            field=models.CharField(choices=[('', ''), ('00', '00'), ('30', '30')], max_length=50, null=True),
        ),
    ]
