# Generated by Django 4.1.1 on 2022-09-09 15:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservas', '0023_transaction_payment_method_transaction_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mensagens',
            new_name='mensagen',
        ),
    ]
