# Generated by Django 4.1.1 on 2022-09-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0024_rename_mensagens_mensagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='expireDate',
            field=models.DateField(null=True),
        ),
    ]
