# Generated by Django 4.1.1 on 2022-09-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0025_transaction_expiredate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('', ''), ('Pending', 'Pending'), ('Success', 'Success'), ('Declined', 'Declined'), ('Refunded', 'Refunded')], max_length=50, null=True),
        ),
    ]
