# Generated by Django 4.1.1 on 2022-09-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0026_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expireDate',
            field=models.DateTimeField(null=True),
        ),
    ]
